# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26f1f763e30f45b922cc7bcfd7c9a135aae8124b0ab67cee2c654844393734d2e86bdb436893d8a7c50dd11ff19d778d37e5d7f0ac1887cffbffbd4f0eb7516

test:
  secret_key_base: 36f53bf9616d2184846a088e4d638e3542d8bd91d57746113be3c6ad53eea4df883dee4e1e3586f8531fb9219b3477eb8d189f12c2eb905691eec861124b6a27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
